FROM telegraf:latest

# Install nano
USER root
RUN apt-get update && apt-get install -y nano

# Set workdir (optional)
WORKDIR /etc/telegraf

# By default the container will run Telegraf
CMD ["telegraf"]
